entities:
  - entity:
    name: 'ardrone0'
    sensors:
      - sensor:
        name: 'fontcam'
        topic: 'aruco/ardrone0/etc'
        transform:
          origin: [0.185, 0, -0.03]
          rot: [0.606109, -0.606109, 0.364187, -0.364187]

  - entity:
    name: 'ardrone1'
    sensors:
    - sensor:
      name: 'fontcam'
      topic: 'aruco/ardrone1/etc'
      transform:
        origin: [0.185, 0, -0.03]
        rot: [0, 2.05949, 4.71239]

markers:
  - marker:
    id: 1
    ref: 'world'
    transform:
      origin: [-0.00452, -0.05223, 0.0089]
      rot: [0, 0, 0, 1]

  - marker:
    id: 4
    ref: 'ardrone1'
    transform:
      origin: [0, -0.25, 0]
      rot: [0, 0, 0, 1]

world:
  - sensor:
    name: 'optitrack0'
    type: 'Global'
    topic: '/Ardrone2SimpleLinModel_HASHMARK_0/pose'
    entity: 'ardrone0'
    sigma: 0.5

  - sensor:
    name: 'optitrack1'
    type: 'Global'
    topic: '/Ardrone2SimpleLinModel_HASHMARK_1/pose'
    entity: 'ardrone1'
    sigma: 0.5
