options:
  # node settings
  loopRate: 60.0 # Hz

  # graph settings
  decayDuration: 0.25 # seconds

  # transform publisher settings
  publishMarkers: true
  publishWorldSensors: true
  publishEntitySensors: true

  # debug
  dbgDumpGraphInterval: 5.0 # seconds
  dbgDumpGraphFilename: '/home/paul/dbgGraph.dot'

entities:
  - entity: world
    markers:
      # This markers position is known in world coordinates
      # We use it to estimate the pose of the drones
      - marker: 0
        transform:
          origin: [-0.00452, -0.05223, 0.0089]
          rot: [-90,180,0] # YPR notation (in degrees)

  - entity: ardrone0
    sensors:
    - sensor: fontcam
      topic: '/aruco_tracker/ardrone0_frontcam/detected_markers'
      transform:
        origin: [0.185, 0, -0.03]
        rot: [0.606109, -0.606109, 0.364187, -0.364187]

  - entity: ardrone1
    sensors:
    - sensor: fontcam
      topic: '/aruco_tracker/ardrone1_frontcam/detected_markers'
      transform:
        origin: [0.185, 0, -0.03]
        rot: [0.606109, -0.606109, 0.364187, -0.364187]
