options:
  # node settings
  loopRate: 60.0 # Hz

  # graph settings
  decayDuration: 0.25 # seconds

  # transform publisher settings
  publishMarkers: true
  publishWorldSensors: true
  publishEntitySensors: true

  # debug
  dbgDumpGraphInterval: 5.0 # seconds
  dbgDumpGraphFilename: '/home/paul/dbgGraph.dot'

entities:
  - entity: world
    sensors:
    - sensor: optitrack0
      topic: '/Ardrone2SimpleLinModel_HASHMARK_0/pose'
      target: ardrone0
      type: 'NonMarkerBased'
      sigma: 0.1

    - sensor: optitrack1
      topic: '/Ardrone2SimpleLinModel_HASHMARK_1/pose'
      target: ardrone1
      type: 'NonMarkerBased'
      sigma: 0.1

  - entity: ardrone0
    sensors:
    - sensor: fontcam
      topic: '/aruco_tracker/ardrone0_frontcam/detected_markers'
      transform: {origin: [0.185, 0, -0.03], rot: [0.606109, -0.606109, 0.364187, -0.364187]}

  - entity: ardrone1
    sensors:
    - sensor: fontcam
      topic: '/aruco_tracker/ardrone1_frontcam/detected_markers'
      transform: {origin: [0.185, 0, -0.03], rot: [0.606109, -0.606109, 0.364187, -0.364187]}

  # This entity is used to detect the position of marker 0
  # It has no physical meaning
  - entity: Marker0Wrapper
    markers:
    - marker: 0
      transform: {origin: [0, 0, 0],  rot: [0, 0, 0, 1]}
