options:
  # node settings
  loopRate: 60.0 # Hz

  # graph settings
  decayDuration: 0.25 # seconds

  # transform publisher settings
  publishMarkers: true
  publishWorldSensors: true
  publishEntitySensors: true

  # debug
  dbgDumpGraphInterval: 5.0 # seconds
  dbgDumpGraphFilename: '/home/paul/dbgGraph.dot'

entities:
  - entity:
    name: 'ardrone0'
    sensors:
      - sensor:
        name: 'fontcam'
        topic: '/aruco_tracker/ardrone0_frontcam/detected_markers'
        transform:
          origin: [0.185, 0, -0.03]
          rot: [0.606109, -0.606109, 0.364187, -0.364187]

  - entity:
    name: 'ardrone1'
    sensors:
    - sensor:
      name: 'fontcam'
      topic: '/aruco_tracker/ardrone1_frontcam/detected_markers'
      transform:
        origin: [0.185, 0, -0.03]
        rot: [0.606109, -0.606109, 0.364187, -0.364187]

  # This entity is used to detect the position of marker 0
  # It has no physical meaning
  - entity:
    name: 'Marker0Wrapper'

markers:
  - marker:
    id: 0
    ref: 'Marker0Wrapper'
    transform:
      origin: [0, 0, 0]
      rot: [0, 0, 0, 1]

world:
  - sensor:
    name: 'optitrack0'
    type: 'Global'
    topic: '/Ardrone2SimpleLinModel_HASHMARK_0/pose'
    entity: 'ardrone0'
    sigma: 0.1

  - sensor:
    name: 'optitrack1'
    type: 'Global'
    topic: '/Ardrone2SimpleLinModel_HASHMARK_1/pose'
    entity: 'ardrone1'
    sigma: 0.1
